from glob import glob

from setuptools import setup

package_name = 'racer_control'

setup(
    name=package_name,
    version='0.1.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages', ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/config', glob('config/*.yaml')),
        ('share/' + package_name + '/launch', glob('launch/*.launch.py')),
        # The racing lines. They live with the controller because the
        # controller is what follows them; frames.RACELINE_DIR resolves this
        # through the ament index. Generated by raceline/optimize_raceline.py
        # on the main branch -- this branch ships the finished artefacts only.
        ('share/' + package_name + '/raceline', glob('raceline/*.csv')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='Abdullah Bin Naeem',
    maintainer_email='abdullahbinnaeempro@gmail.com',
    description='Pure pursuit path following and steering calibration',
    license='BSD',
    entry_points={
        'console_scripts': [
            'pure_pursuit = racer_control.pure_pursuit:main',
            'calibrate_steering = racer_control.calibrate_steering:main',
        ],
    },
)
