#!/usr/bin/env python3

"""Write an AMCL parameter file that is the shipped config plus one change.

    python3 make_variant.py <shipped amcl.yaml> <out.yaml> max_beams=360,z_hit=0.8

nav2 takes exactly ONE parameter file per node, so a partial override file
would silently leave every unmentioned parameter at the nav2 default rather
than at ours -- an "A/B" that changed twenty things at once. Generating the
variant from the shipped file instead means a variant is a genuine one-line
diff, and it can never drift from what actually races.

config/amcl.yaml itself is never touched: it ships inside the submission image.
"""

import sys

import yaml


def coerce(v):
    """'360' -> int, '0.05' -> float, 'true' -> bool, anything else -> str.

    The type has to match what nav2 declared or the parameter is rejected at
    load, so this cannot just hand everything over as a string.
    """
    low = v.strip().lower()
    if low in ('true', 'false'):
        return low == 'true'
    for cast in (int, float):
        try:
            return cast(v)
        except ValueError:
            pass
    return v


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    src, dst, spec = sys.argv[1:]
    doc = yaml.safe_load(open(src))
    params = doc['amcl']['ros__parameters']
    applied = []
    if spec not in ('-', ''):
        for pair in spec.split(','):
            if not pair.strip():
                continue
            k, _, v = pair.partition('=')
            k = k.strip()
            if k not in params:
                sys.exit(f'{src} has no parameter {k!r} -- refusing to add one, '
                         f'since a typo would silently do nothing')
            params[k] = coerce(v)
            applied.append(f'{k}={params[k]}')
    with open(dst, 'w') as f:
        f.write(f'# GENERATED by make_variant.py from {src}\n')
        f.write(f'# changed: {", ".join(applied) if applied else "nothing"}\n')
        yaml.safe_dump(doc, f, default_flow_style=False, sort_keys=False)
    print(', '.join(applied) if applied else 'baseline (no overrides)')


if __name__ == '__main__':
    main()
