import os
from glob import glob

from setuptools import find_packages, setup

package_name = 'roboracer_stack'


def track_data(subdir, pattern='*'):
    """Install `subdir/`, plus one level of per-track subdirectories under it.

    Track assets used to be a flat directory, so `glob('maps/*')` was enough.
    They are now scoped by track -- maps/icra/, raceline/icra/ -- and that glob
    yields the DIRECTORY maps/icra, which data_files cannot copy: setuptools
    tries to open it as a file and the build dies with IsADirectoryError. So
    files and subdirectories are enumerated separately.

    One level only, and by discovery rather than by name: adding a track means
    creating maps/<name>/ and raceline/<name>/, not editing this file.
    """
    here = os.path.join('share', package_name, subdir)
    files = lambda d: [p for p in glob(os.path.join(d, pattern))
                       if os.path.isfile(p)]
    entries = [(here, files(subdir))]
    entries += [(os.path.join(here, os.path.basename(d)), files(d))
                for d in sorted(glob(os.path.join(subdir, '*')))
                if os.path.isdir(d)]
    return entries


setup(
    name=package_name,
    version='0.1.0',
    # find_packages, not [package_name]: the code is split into subsystem
    # submodules (common, perception, localization, planning, control, mapping)
    # and a bare list would install only the top-level __init__.py.
    packages=find_packages(exclude=['test', 'tools']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        (os.path.join('share', package_name, 'launch'), glob('launch/*.launch.py')),
        (os.path.join('share', package_name, 'config'),
            glob('config/*.yaml') + glob('config/*.xml')),
        (os.path.join('share', package_name, 'rviz'), glob('rviz/*.rviz')),
        # The tracks, baked in. common/frames.py finds all of this through the
        # ament index, so nothing depends on where the repo was cloned.
        # Porto's grid sits at the top level (where it has always been); every
        # track added since is a subdirectory, maps/icra among them.
        *track_data('maps'),
        # The racing lines. Generated by raceline/optimize_raceline.py on the
        # main branch; this branch ships the finished artefacts only. CSVs only
        # -- PROFILES.md is documentation and does not belong in the image.
        *track_data('raceline', '*.csv'),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='Abdullah Bin Naeem',
    maintainer_email='abdullahbinnaeempro@gmail.com',
    description='Localization, planning and control for the AutoDRIVE RoboRacer',
    license='BSD',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'dead_reckoning = roboracer_stack.localization.dead_reckoning:main',
            'localization_bootstrap = roboracer_stack.localization.bootstrap:main',
            'localization_error = roboracer_stack.localization.localization_error:main',
            'log_localization = roboracer_stack.localization.log_localization:main',
            'pure_pursuit = roboracer_stack.control.pure_pursuit:main',
            'calibrate_steering = roboracer_stack.control.calibrate_steering:main',
            'map_publisher = roboracer_stack.mapping.map_publisher:main',
        ],
    },
)
