import os
from glob import glob

from setuptools import find_packages, setup

package_name = 'roboracer_stack'

setup(
    name=package_name,
    version='0.1.0',
    # find_packages, not [package_name]: the code is split into subsystem
    # submodules (common, localization, planning, control)
    # and a bare list would install only the top-level __init__.py.
    packages=find_packages(),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        (os.path.join('share', package_name, 'launch'), glob('launch/*.launch.py')),
        (os.path.join('share', package_name, 'config'),
            glob('config/*.yaml') + glob('config/*.xml')),
        # The track, baked in. common/frames.py finds both of these through the
        # ament index, so nothing depends on where the repo was cloned.
        (os.path.join('share', package_name, 'maps'), glob('maps/*')),
        # The racing lines. Generated by raceline/optimize_raceline.py on the
        # main branch; this branch ships the finished artefacts only.
        (os.path.join('share', package_name, 'raceline'), glob('raceline/*.csv')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='Abdullah Bin Naeem',
    maintainer_email='abdullahbinnaeempro@gmail.com',
    description='Localization, planning and control for the AutoDRIVE RoboRacer',
    license='BSD',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'dead_reckoning = roboracer_stack.localization.dead_reckoning:main',
            'localization_bootstrap = roboracer_stack.localization.bootstrap:main',
            'pure_pursuit = roboracer_stack.control.pure_pursuit:main',
        ],
    },
)
